import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleSubmit = async (event) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault()

    var content = event.target.content.value

    if (content) {
      const searchRegExp = /<div class="separator" style="clear: both;"><a.*><img/g;
      const replaceWith = '<img';
      const result = content.replace(searchRegExp, replaceWith);

      searchRegExp = /<\/a><\/div>/g;
      replaceWith = '';
      result = result.replace(searchRegExp, replaceWith);

      searchRegExp = /" src="/g;
      replaceWith = '" width="100%" src="';
      result = result.replace(searchRegExp, replaceWith);

      searchRegExp = /s1600/g;
      replaceWith = '-rw';
      result = result.replace(searchRegExp, replaceWith);

      searchRegExp = /<iframe width=".*" height/g;
      replaceWith = '<iframe height';
      result = result.replace(searchRegExp, replaceWith);

      var lines = result.split("\n");
      for(var i=0; i<lines.length; i++) {
        lines[i] = "<p>" + lines[i] + "</p>";
      }

      result = lines.join("\n");

      event.target.result.value = result
    }

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog
        </h1>

        <form onSubmit={handleSubmit} className={styles.form}>
          
          <label htmlFor="content">add content</label>
          <textarea id="content" name="content"></textarea>

          <label htmlFor="content">this result</label>
          <textarea id="result" name="result"></textarea>

          <div>
            <button type="reset">Reset</button>
            <button type="submit">Submit</button>
          </div>
        </form>
        
      </main>

    </div>
  )
}
